### ISSUE TITLE
Image/Gifs feature in timers

### ISSUE THREAD

**Issue by robsoncruzs** [timer-machine/timer-machine-android#64] opened 2023-11-09 18:25 UTC
In the list of resources (music, vribration, screen, halt, voice, etc.) there could also be an image/gif to insert. And when activated, it appears on the timer execution screen.

**Comment by DeweyReed** [comment] 2023-11-09 23:54
Duplicate of #30 

I'll see what I can do as soon as I have some time.

**Closed by DeweyReed** 2023-11-09 23:54 UTC
